kind: ReplicationController
apiVersion: v1
metadata:
  name: zeppelin-controller
  namespace: spark-cluster
spec:
  replicas: 1
  selector:
    component: zeppelin
  template:
    metadata:
      labels:
        component: zeppelin
    spec:
      containers:
        - name: zeppelin
          image: harbor-001.jimmysong.io/library/zeppelin:0.7.1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
